data:
  dataset: "grab"
  dataset_path: "./data/grab"
  num_workers: 4
  normalize: true
  split: "train"
  mano_path: "mano"
  object_sample: 2048
  contact_th: 0.11
  test_samples: 20
  random_rot: False

diffusion:
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.01
  num_timesteps: 129

model:
  name: "PhysHandGen"
  hid_dim: 2056
  emd_dim: 512
  coords_dim: 64
  num_layer: 7
  n_head: 4
  dropout: 0.10
  w: 0.0
  ema_rate: 0.999
  ema: False
  var_type: fixedsmall
  skips: [1, 3, 5, 6]
  downsample: 1
  obj_feature: 6
  obj_feature_keys:
    - "normal"

  latentD: 16
  n_neurons: 256
  pointnet_hc: 64

  robustkl: True
  kl_coef: 0.05

hand_model_params:
  activation: igr
  beta: 100
  dims:
    - 64
    - 64
    - 64
    - 64
  dropout_layers: []
  dropout_prob: 0.0
  fft: true
  fft_dim: 10
  fft_progressive_factor: 5.0
  final_out_dim: 1
  geometric_init: true
  groups: 1
  init_std: 1.0e-06
  latent_dropout: false
  latent_in: []
  latent_size: 42
  norm_layers:
    - 0
    - 1
    - 2
    - 3
  normalization: weight
  query_dim: 3
  query_in_all: false
  radius_init: 0.25
  residual: false
pose_size: 32

train:
  batch_size: 32
  optimizer: "Adam"
  lr: 1.0e-3
  lr_gamma: 0.8
  scheduler_step: 5
  max_epochs: 100
  vis_every_n_batch: 100
  val_every_n_epochs: 2

val:
  vis_every_n_batch: 40
  batch_size: 64

test:
  batch_size: 20
  n_samples: 1
  vis_every_n_batch: 10
